name: Sync Fork

on:
  workflow_dispatch: # on button click

permissions: write-all

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: wasmerio
          base: main
          head: main
