name: Sync Fork

on:
  workflow_dispatch: # on button click

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: wasmerio
          base: main
          head: main
